### ISSUE TITLE
Invalid CSV line for probes.txt

### ISSUE THREAD

**Issue by dragonxtek** [dioptra-io/caracal#56]
I replicate probes.txt in the example but it didn't work

![Screenshot from 2023-06-11 00-32-45](https://github.com/dioptra-io/caracal/assets/10552658/1fcf0a0f-f04b-49e0-9e95-96295dd0d0af)

The CSV standar did change?

**Comment by SaiedKazemi** [comment]
@dragonxtek Sorry for the long delay.  I hope your issue has been resolved since you reported it back in June.

Unfortunately, we do not have resources to provide support at this point.  I think it is best to close this issue at this point unless @kvermeul has time to look into it and prefers to keep it open.

**Comment by kvermeul** [comment]
Hello @dragonxtek I guess you are missing a protocol in your lines in probes.txt?

**Comment by SaiedKazemi** [comment]
@dragonxtek I am closing this issue.  If you are still facing problem, please open a new issue.
